name: test-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo:latest
          ##adding :latest to the tag will label the Docker image as the latest version. This is a common convention to indicate the most recent build of the image.
          ##In here we have also specified which Docker repo to push the image to. This is done by using the DOCKERHUB_USERNAME secret.
          registry: docker.io
          ##As of now we are using the Docker Hub registry. If you are using a different registry, you can specify it here. As an example we can directly push it to an AWS ECR registry (TO use within an EC2).
          dockerfile: Dockerfile